utils::globalVariables(c(
  '.action', '.affected', '.metric', '.reference', '.tooltip', '.value',
  'action_policy', 'attendance_issue', 'attending', 'council', 'district',
  'burden', 'color',
  'expected_positive', 'facility', 'facility_id',
  'facilities', 'facilities_over_threshold', 'flagged_rows',
  'flag_all_negative_large_n', 'flag_all_positive_large_n',
  'flag_attendance_issue', 'flag_attending_negative',
  'flag_any_qc_issue', 'flag_combined_tested_prevalence_issue',
  'flag_core_invalid', 'flag_exclude_authorized',
  'flag_invalid_logical', 'flag_isolated_extreme',
  'flag_large_monthly_prevalence_change', 'flag_missing_tested_or_positive',
  'flag_positive_gt_tested', 'flag_positive_negative',
  'flag_prevalence_extreme', 'flag_prevalence_only_issue',
  'flag_raw_prevalence_bound',
  'flag_resid_extreme', 'flag_review_recommended', 'flag_sensitivity',
  'flag_tested_extreme_high', 'flag_tested_extreme_low',
  'flag_tested_high_ratio', 'flag_tested_high_z',
  'flag_tested_gt_attending', 'flag_tested_large_drop', 'flag_tested_large_jump', 'flag_tested_negative',
  'flag_tested_only_issue', 'flag_tested_volume_extreme',
  'flag_tested_low_ratio', 'flag_tested_low_z',
  'flag_tested_zero_unusual', 'flag_zero_tested_positive', 'injected_error',
  'hover', 'id', 'label', 'level', 'lp', 'month', 'month_date', 'month_lag',
  'month_num', 'monthly_prev_change', 'n',
  'multiple_signal_issue', 'n_any_qc_issue', 'n_month',
  'n_qc_signal_domains', 'next_extreme', 'next_month_date',
  'next_month_is_adjacent', 'p', 'p_hat',
  'pct_any_qc_issue', 'pearson_resid', 'positive',
  'prev_extreme', 'prev_lag', 'prev_month_date', 'prev_month_is_adjacent',
  'parent', 'pct_all', 'prevalence', 'prevalence_issue',
  'previous_month_is_adjacent', 'proportion', 'proportion_over_threshold',
  'qc_action', 'qc_reason', 'source_row',
  'region', 'review_priority', 'season', 'state', 'tested', 'tested_issue', 'tested_prev',
  'residual_cutoff', 'tested_baseline_n', 'tested_baseline_ready',
  'tested_lag', 'tested_mad_adjusted', 'tested_robust_z',
  'tested_roll_mad', 'tested_roll_median',
  'tested_to_prev_ratio', 'tested_to_roll_ratio', 'time_index',
  'total_positive_after_authorized_exclusions', 'total_positive_before_qc',
  'total_rows', 'total_tested_after_authorized_exclusions',
  'total_tested_before_qc'
))
